export const taxKeywords = [
  "pajak penghasilan",
  "pph",
  "pph 21",
  "pph 22",
  "pph 23",
  "pph 24",
  "pph 25",
  "pph 29",
  "penghasilan kena pajak",
  "penghasilan bruto",
  "penghasilan neto",
  "ptkp",
  "pemotongan pph",
  "tarif pph",
  "bukti potong",
  "taxable income",
  "income tax",
  "withholding tax",
  "gross up",
  "netto",
  "dividen",
  "penghasilan final",
  "penghasilan tidak kena pajak",

  // Pajak Pertambahan Nilai (PPN)
  "pajak pertambahan nilai",
  "ppn",
  "pajak masukan",
  "pajak keluaran",
  "pengusaha kena pajak",
  "pkp",
  "faktur pajak",
  "faktur elektronik",
  "ppn 11%",
  "value added tax",
  "vat",
  "tax invoice",

  // Pajak Bumi dan Bangunan (PBB)
  "pbb",
  "pajak bumi dan bangunan",
  "sppt",
  "njop",
  "njkp",
  "objek pajak",
  "subjek pajak",
  "pbb perkotaan",
  "pbb pedesaan",
  "land tax",
  "building tax",

  // Pajak Kendaraan Bermotor
  "pajak kendaraan",
  "pkb",
  "stnk",
  "bpkb",
  "samsat",
  "pajak motor",
  "pajak mobil",
  "plat nomor",
  "pajak progresif",
  "kendaraan bermotor",
  "vehicle tax",
  "car tax",
  "motorcycle tax",

  // Tax Planning dan Optimasi
  "tax planning",
  "perencanaan pajak",
  "efisiensi pajak",
  "optimalisasi pajak",
  "transfer pricing",
  "insentif pajak",
  "fasilitas pajak",
  "tax holiday",
  "tax allowance",
  "pemanfaatan rugi fiskal",
  "kompensasi kerugian",
  "akumulasi rugi",
  "rugi fiskal",
  "biaya yang dapat dikurangkan",
  "deductible expense",

  // NPWP dan Identitas Pajak
  "npwp",
  "npwp pribadi",
  "npwp badan",
  "cek npwp",
  "pemadanan npwp nik",
  "daftar npwp",
  "tax id",
  "tax identification number",
  "taxpayer id",

  // Pelaporan Pajak & e-Filing
  "e-filing",
  "e-bupot",
  "efin",
  "e-form",
  "e-billing",
  "e-spt",
  "djponline",
  "spt tahunan",
  "spt masa",
  "lapor spt",
  "pembetulan spt",
  "spt online",
  "filing tax",
  "submit tax",
  "tax form",
  "online filing",
  "spt elektronik",

  // Pembayaran Pajak
  "pembayaran pajak",
  "setor pajak",
  "id billing",
  "kode billing",
  "ssp",
  "ssp elektronik",
  "tax payment",
  "billing code",
  "pay tax",

  // Tarif, DPP, dan Penghitungan Pajak
  "tarif pajak",
  "dpp",
  "dasar pengenaan pajak",
  "penghasilan tidak kena pajak",
  "kredit pajak",
  "kewajiban pajak",
  "perhitungan pajak",
  "simulasi pajak",
  "tax calculator",
  "tax simulation",
  "estimasi pajak",

  // Sanksi dan Denda
  "sanksi pajak",
  "denda pajak",
  "sanksi administrasi",
  "keterlambatan lapor spt",
  "penalty",
  "tax fine",
  "tax sanction",
  "late filing fee",

  // Tax Amnesty & PPS
  "tax amnesty",
  "pengampunan pajak",
  "pps",
  "program pengungkapan sukarela",
  "pengungkapan harta",
  "voluntary disclosure",
  "tax forgiveness",
  "tax relief",

  // DJP dan Pelayanan Pajak
  "direktorat jenderal pajak",
  "djp",
  "kpp",
  "kantor pajak",
  "layanan pajak",
  "helpdesk pajak",
  "petugas pajak",
  "np2",
  "surat teguran",
  "konsultasi pajak",

  // Typo & variasi umum
  "pejak",
  "pph21",
  "ppn11",
  "npwwp",
  "efillling",
  "npw",
  "efin pajak",
  "sppt pbb",
  "e billing",
  "djponline pajak",

  // Konteks umum tapi khas pajak
  "lapor",
  "setor",
  "tarif",
  "penghasilan",
  "harta",
  "utang",
  "bukti",
  "rekening koran",
  "pembukuan",
  "spt",
  "tahun pajak",
  "masa pajak",
  "kewajiban",
  "pemotong",
  "pelapor",
  "pengusaha",
  "badan usaha",
  "pt",
  "cv",

  // Bahasa Inggris sehari-hari yang relevan
  "report tax",
  "pay tax",
  "how to file tax",
  "tax calculator indonesia",
  "indonesia tax",
  "npwp registration",
  "file spt",
  "login djponline",
  "indonesia pph",
  "indonesia ppn",
  "indonesia tax deadline",
];
